# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 1m
  issues-exit-code: 1
  tests: true
  go: "1.25"
  relative-path-mode: wd

linters:
  default: standard

  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - dupword
    - errname
    - exhaustive
    - funcorder
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - grouper
    - lll
    - makezero
    - mnd
    - modernize
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofumpt
    - gci
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
